### PR TITLE
Use new s3fs repo & fixes data_from_bag option

### PR DESCRIPTION
**Pull request by DarkGigaByte**
You can use all AWS regions in the new s3fs version because it supports AWS Api in Version 4.

### CODE REVIEW

**Comment by joaogbcravo** [comment]
:+1:

**Comment by joaogbcravo** [comment]
@twilson63  can you create a release of this merge in supermarket? Or at least create a tag in github ? 

Cheers,
João

**Comment by twilson63** [comment]
Definitely tag, re supermarket, not aware of the process happy to make you
a collaborator to make that happen

Sent from my iPhone

On Nov 23, 2015, at 7:30 AM, joaogbcravo <notifications@github.com> wrote:

@twilson63 <https://github.com/twilson63> can you create a release of this
merge in supermarket? Or at least create a tag in github ?

Cheers,
João

—
Reply to this email directly or view it on GitHub
<https://github.com/twilson63/s3fs-recipe/pull/26#issuecomment-158920378>.

**Comment by gsaslis** [comment]
@twilson63 i can help with the release if you like.  : ) 

I've used [stove](https://github.com/sethvargo/stove) before for that

**Comment by twilson63** [comment]
@gsaslis 

That would be awesome, I just made you a collaborator! Let me know, if you need anything else.

Thx

Tom

**Comment by DarkGigaByte** [comment]
Thanks for merge and release!

**Comment by gsaslis** [comment]
@twilson63:  Thanks Tom - no worries. Just need you to also add me as a collaborator on supermarket.chef.io as well, as I currently don't have permission to release the new version there. 

if I do manage to find some time over the next few days, I was also planning to put together a PR that uses Chef Vault to securely retrieve the credentials, etc.

**Comment by twilson63** [comment]
Cool

Done!

Thanks

Tom

On Tue, Feb 2, 2016 at 10:32 AM, Yorgos Saslis <notifications@github.com>
wrote:

> @twilson63 <https://github.com/twilson63>: Thanks Tom - no worries. Just
> need you to also add me as a collaborator on supermarket.chef.io as well,
> as I currently don't have permission to release the new version there.
>
> if I do manage to find some time over the next few days, I was also
> planning to put together a PR that uses Chef Vault to securely retrieve the
> credentials, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twilson63/s3fs-recipe/pull/26#issuecomment-178638540>.
>



-- 
Tom Wilson
Jack Russell Software, A Tabula Rasa Healthcare Division
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
<http://www.jackhq.com/calendar>

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by gsaslis** [comment]
:+1: 

https://supermarket.chef.io/cookbooks/s3fs ;)

**Comment by twilson63** [comment]
Thank you!!!!!

On Tue, Feb 2, 2016 at 11:47 AM, Yorgos Saslis <notifications@github.com>
wrote:

> [image: :+1:]
>
> https://supermarket.chef.io/cookbooks/s3fs ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twilson63/s3fs-recipe/pull/26#issuecomment-178682387>.
>



-- 
Tom Wilson
Jack Russell Software, A Tabula Rasa Healthcare Division
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
<http://www.jackhq.com/calendar>

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Pull request merged**
